import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { AnalysisResult } from '../types';

function severityColor(s: string) {
  if (s === 'error') return '#B33A2E';
  if (s === 'warning') return '#C47A1A';
  return '#2F6B3A';
}

export function buildReportHtml(result: AnalysisResult): string {
  const findingsHtml = result.findings
    .map(
      (f) => `
      <div style="border-left:4px solid ${severityColor(f.severity)};padding:10px 12px;margin:8px 0;background:#FAFBFO;border-radius:0 8px 8px 0;">
        <div style="font-weight:600;color:#1A1F1C;">${escapeHtml(f.title)}</div>
        <div style="font-size:13px;color:#5A635C;margin-top:4px;">${escapeHtml(f.detail)}</div>
      </div>`
    )
    .join('');

  const medsHtml = result.medicines
    .map(
      (m) =>
        `<tr><td>${escapeHtml(m.name)}</td><td>${escapeHtml(m.doseMg)} ${escapeHtml(m.unit || 'mg')}</td><td>${escapeHtml(m.frequency)}</td></tr>`
    )
    .join('');

  const altsHtml = result.alternatives
    .map(
      (a) => `
      <div style="margin:8px 0;padding:10px;border:1px solid #D5DBD4;border-radius:10px;">
        <div><strong>${escapeHtml(a.original)}</strong> → <strong style="color:#0E6E63;">${escapeHtml(a.suggested)}</strong></div>
        <div style="font-size:13px;color:#5A635C;">${escapeHtml(a.reason)}</div>
        <div style="font-size:12px;margin-top:6px;">
          ${a.truemedsUrl ? `<a href="${a.truemedsUrl}">Truemeds</a>` : ''}
          ${a.tata1mgUrl ? ` · <a href="${a.tata1mgUrl}">Tata 1mg</a>` : ''}
        </div>
      </div>`
    )
    .join('');

  const p = result.patientSnapshot;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: -apple-system, 'IBM Plex Sans', Helvetica, Arial, sans-serif; background:#F4F6F2; color:#1A1F1C; padding:24px; }
    .header { border-bottom:2px solid #0E6E63; padding-bottom:12px; margin-bottom:20px; }
    .brand { color:#0E6E63; font-size:22px; font-weight:700; letter-spacing:-0.3px; }
    .sub { color:#5A635C; font-size:12px; text-transform:uppercase; letter-spacing:0.8px; }
    .score { font-size:48px; font-weight:700; color:${result.riskLevel === 'HIGH' ? '#B33A2E' : result.riskLevel === 'MODERATE' ? '#C47A1A' : '#2F6B3A'}; }
    table { width:100%; border-collapse:collapse; margin:12px 0; }
    th, td { text-align:left; padding:8px; border-bottom:1px solid #D5DBD4; font-size:13px; }
    th { font-family: monospace; font-size:11px; text-transform:uppercase; color:#5A635C; }
    .footer { margin-top:32px; font-size:11px; color:#8A938C; border-top:1px solid #D5DBD4; padding-top:12px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">Rx/Check</div>
    <div class="sub">AI Prescription Error Detector · Clinical Safety Report</div>
  </div>

  <p>This report was generated by <strong>Rx/Check</strong>. It is a decision-support aid only and does not replace professional clinical judgment. Verify all drugs before use.</p>

  <div style="display:flex;gap:24px;align-items:center;margin:16px 0;">
    <div>
      <div class="sub">Safety score</div>
      <div class="score">${result.score}</div>
    </div>
    <div>
      <div class="sub">Risk level</div>
      <div style="font-size:20px;font-weight:600;">${result.riskLevel}</div>
      <div style="font-size:12px;color:#5A635C;">${new Date(result.generatedAt).toLocaleString()}</div>
    </div>
  </div>

  <h3 style="color:#0E6E63;">Patient</h3>
  <p style="font-size:14px;">
    ${escapeHtml(p.name || '—')} · Age ${escapeHtml(p.age || '—')} · Weight ${escapeHtml(p.weight || '—')} kg · ${escapeHtml(p.gender || '—')}
    ${p.pregnant ? ' · Pregnant' : ''}
    ${p.kidneyDisease ? ' · Kidney disease' : ''}
    ${p.liverDisease ? ' · Liver disease' : ''}
    ${p.allergies ? `<br/>Allergies: ${escapeHtml(p.allergies)}` : ''}
  </p>

  <h3 style="color:#0E6E63;">Medicines</h3>
  <table>
    <thead><tr><th>Name</th><th>Dose</th><th>Frequency</th></tr></thead>
    <tbody>${medsHtml}</tbody>
  </table>

  <h3 style="color:#0E6E63;">Findings</h3>
  ${findingsHtml || '<p style="color:#2F6B3A;">No critical issues flagged.</p>'}

  ${result.alternatives.length ? `<h3 style="color:#0E6E63;">Suggested alternatives</h3>${altsHtml}` : ''}

  <div class="footer">
    Rx/Check verifies listed drugs for interaction, dosage, allergy, contraindication, duplicate therapy, pregnancy, and organ-function considerations using rule-based and AI-assisted checks.
    Always confirm with a licensed clinician or pharmacist. Not for emergency use.
  </div>
</body>
</html>`;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export async function exportPdfReport(result: AnalysisResult) {
  const html = buildReportHtml(result);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Rx/Check Safety Report',
      UTI: 'com.adobe.pdf',
    });
  }
  return uri;
}
