import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, ActivityIndicator } from 'react-native';
import { useRouter } from 'expo-router';
import { PaperBackground } from '../src/components/PaperBackground';
import { Stepper } from '../src/components/Stepper';
import { ScoreGauge } from '../src/components/ScoreGauge';
import { FindingCard } from '../src/components/FindingCard';
import { colors, typography, spacing, radius } from '../src/theme';
import { usePrescriptionStore } from '../src/store/prescriptionStore';
import { exportPdfReport } from '../src/services/pdfReport';

export default function ReportScreen() {
  const router = useRouter();
  const analysis = usePrescriptionStore((s) => s.analysis);
  const resetFlow = usePrescriptionStore((s) => s.resetFlow);
  const [exporting, setExporting] = useState(false);

  if (!analysis) {
    return (
      <PaperBackground>
        <View style={styles.empty}>
          <Text style={styles.h}>No report</Text>
          <TouchableOpacity onPress={() => router.replace('/')}>
            <Text style={{ color: colors.teal }}>Home</Text>
          </TouchableOpacity>
        </View>
      </PaperBackground>
    );
  }

  const onExport = async () => {
    setExporting(true);
    try {
      await exportPdfReport(analysis);
    } finally {
      setExporting(false);
    }
  };

  const p = analysis.patientSnapshot;

  return (
    <PaperBackground>
      <Stepper current="report" />
      <ScrollView contentContainerStyle={styles.pad}>
        <Text style={styles.brand}>Rx/Check</Text>
        <Text style={styles.sub}>AI Prescription Error Detector · Safety Report</Text>
        <Text style={styles.verify}>
          This report was generated by Rx/Check to help verify whether the listed drugs are appropriate to use for this patient profile. It is decision support only — not a prescription or medical advice.
        </Text>

        <ScoreGauge score={analysis.score} riskLevel={analysis.riskLevel} />

        <Text style={styles.section}>Patient</Text>
        <Text style={styles.body}>
          {p.name || '—'} · Age {p.age || '—'} · {p.weight || '—'} kg · {p.gender || '—'}
          {p.pregnant ? ' · Pregnant' : ''}
          {p.kidneyDisease ? ' · Kidney disease' : ''}
          {p.liverDisease ? ' · Liver disease' : ''}
        </Text>
        {p.allergies ? <Text style={styles.body}>Allergies: {p.allergies}</Text> : null}

        <Text style={styles.section}>Medicines reviewed</Text>
        {analysis.medicines.map((m) => (
          <View key={m.id} style={styles.medChip}>
            <Text style={styles.medName}>{m.name}</Text>
            <Text style={styles.medDose}>
              {m.doseMg} {m.unit || 'mg'} · {m.frequency}
            </Text>
          </View>
        ))}

        <Text style={styles.section}>Findings</Text>
        {analysis.findings.map((f) => (
          <FindingCard key={f.id} finding={f} />
        ))}

        <TouchableOpacity style={styles.cta} onPress={onExport} disabled={exporting}>
          {exporting ? (
            <ActivityIndicator color={colors.white} />
          ) : (
            <Text style={styles.ctaText}>Export PDF report</Text>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.secondary}
          onPress={() => {
            resetFlow();
            router.replace('/');
          }}
        >
          <Text style={styles.secondaryText}>New scan</Text>
        </TouchableOpacity>
      </ScrollView>
    </PaperBackground>
  );
}

const styles = StyleSheet.create({
  pad: { padding: spacing.lg, paddingBottom: 48 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  brand: { ...typography.hero, color: colors.teal, fontSize: 24 },
  sub: { ...typography.label, color: colors.textSecondary, marginBottom: spacing.md },
  verify: { ...typography.bodySmall, color: colors.textSecondary, marginBottom: spacing.lg },
  section: { ...typography.label, color: colors.teal, marginTop: spacing.lg, marginBottom: 8 },
  body: { ...typography.body, color: colors.textPrimary },
  medChip: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  medName: { ...typography.body, fontWeight: '600', color: colors.textPrimary },
  medDose: { ...typography.mono, color: colors.textSecondary, marginTop: 2 },
  cta: {
    marginTop: spacing.xl,
    backgroundColor: colors.teal,
    borderRadius: radius.md,
    paddingVertical: 16,
    alignItems: 'center',
  },
  ctaText: { ...typography.h2, color: colors.white },
  secondary: {
    marginTop: spacing.md,
    borderWidth: 1.5,
    borderColor: colors.teal,
    borderRadius: radius.md,
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryText: { ...typography.h2, color: colors.teal },
  h: { ...typography.h1 },
});
